from Coleccion import Coleccion
if __name__ == '__main__':
    print('\n')
    print('-----------Hay 8 empleados en los csv. 4 en planta, 2 en externos y 2 en contratados-----------')
    print('\n')
    dimension = int(input('Ingrese el tamaño que debe tener la coleccion para cargar los empleados:'))
    manejador = Coleccion(dimension)
    manejador.initc(dimension)
    print('\n')
    manejador.mostrar()
    print('Inciso 1'.center(30,'-'))
    print('\n')
    manejador.mostrarcontratados()
    dni = int(input('Ingrese dni del empleado:'))
    canh = int(input('Ingrese la cantidad de horas trabajadas del empleado:'))
    manejador.Registrarhoras(dni,canh)
    print('Inciso 3'.center(30,'-'))
    print('\n')
    manejador.ayudaeconomica()
    print('Inciso 4'.center(30,'-'))
    print('\n')
    manejador.mostrarsueldo()